"""empty message

Revision ID: 9f6aca5d1995
Revises: 9553200349ac
Create Date: 2025-01-14 14:13:31.652039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f6aca5d1995'
down_revision = '9553200349ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_history')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('patient_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prediction_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('visit_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('follow_up_notes', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], name='patient_history_ibfk_1'),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], name='patient_history_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
